el19 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的")
el19.click()
el20 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="语言设置")
el20.click()
el21 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"应用语言\n中文\")")
el21.click()
el22 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="English")
el22.click()
el23 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Button")
el23.click()
el24 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Home")
el24.click()
el25 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="AI Assistant")
el25.click()
el26 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="History")
el26.click()
el27 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Profile")
el27.click()
el28 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="Language Settings")
el28.click()
el29 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"App Language\nEnglish\")")
el29.click()
el30 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="中文")
el30.click()
el31 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Button")
el31.click()
