el25 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"翻译中心\n面对面，无缝交流\")")
el25.click()
el26 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="开始单向模式")
el26.click()
el27 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="简体中文")
el27.click()
el28 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"日本語\nJapanese\")")
el28.click()
el29 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(8)")
el29.click()
el30 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(8)")
el30.click()
