el4 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"翻译中心\n面对面，无缝交流\")")
el4.click()
el5 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="开始手机模式")
el5.click()
el6 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="English")
el6.click()
el7 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"中文（简体）\nChinese (Simplified)\")")
el7.click()
el8 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="简体中文")
el8.click()
el9 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"English\nEnglish\")")
el9.click()
el10 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="手机麦克风")
el10.click()
