el55 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的")
el55.click()
el56 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的账户")
el56.click()
el57 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="登出")
el57.click()
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(704, 1336)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.pause(0.1)
actions.w3c_actions.pointer_action.release()
actions.perform()

el58 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="点击登录")
el58.click()
el59 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.EditText\").instance(0)")
el59.click()
el59.send_keys("2833741438@qq.com")
el60 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.EditText\").instance(1)")
el60.click()
el60.clear()
el60.send_keys("Aa1394939@")
el61 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(0)")
el61.click()
el62 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.CheckBox")
el62.click()
el63 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="登录")
el63.click()
