el17 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"会议记录\n转录和总结\")")
el17.click()
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(615, 467)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.pause(0.1)
actions.w3c_actions.pointer_action.release()
actions.perform()

el18 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(8)")
el18.click()
el19 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(5)")
el19.click()
el20 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="【会议记录】05-28 15:51")
el20.click()
el21 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(8)")
el21.click()
el22 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.EditText")
el22.click()
el22.clear()
el23 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.EditText")
el23.click()
el23.send_keys("123")
el24 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="确定")
el24.click()
