el1 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的")
el1.click()
el2 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的账户")
el2.click()
el3 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.ImageView")
el3.click()
el4 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="从相册选择")
el4.click()
el5 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(24)")
el5.click()
el6 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(6)")
el6.click()
el7 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="提交")
el7.click()

