el1 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的")
el1.click()
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(517, 478)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.move_to_location(500, 1660)
actions.w3c_actions.pointer_action.release()
actions.perform()

el2 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的账户")
el2.click()
el3 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"用户名\n12312332123123321231233212312332\")")
el3.click()
el4 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.EditText")
el4.click()
el4.clear()
el5 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.EditText")
el5.click()
el5.send_keys("9896")
el6 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="确定")
el6.click()
el7 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="提交")
el7.click()

