driver.execute_script('mobile:pressKey', {"keycode": 4})
el7 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"会议记录\n转录和总结\")")
el7.click()
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(523, 461)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.pause(0.1)
actions.w3c_actions.pointer_action.release()
actions.perform()

el8 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(9)")
el8.click()
el9 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.EditText")
el9.click()
el9.clear()
el9.send_keys("12111")
el10 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="确定")
el10.click()
