el11 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的")
el11.click()
el12 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的账户")
el12.click()
el13 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.ImageView")
el13.click()
el14 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="拍照")
el14.click()
el15 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="快门")
el15.click()
el16 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="完成")
el16.click()
el17 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="提交")
el17.click()
