el32 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的")
el32.click()
el33 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的账户")
el33.click()
el34 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"生日\n2002-10-05\")")
el34.click()
el35 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="上个月")
el35.click()
el36 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="18, 2002年9月18日星期三")
el36.click()
el37 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="确定")
el37.click()
el38 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="提交")
el38.click()

