el51 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="历史")
el51.click()
el52 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(5)")
el52.click()
el53 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.EditText")
el53.click()
el53.clear()
el53.send_keys("简体中文")
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(472, 592)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.pause(0.1)
actions.w3c_actions.pointer_action.release()
actions.perform()

el54 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Button")
el54.click()
