el63 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"睡眠模式\n白噪音和睡眠音乐，帮助您放松休息。\")")
el63.click()
el64 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(4)")
el64.click()
el65 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="睡眠")
el65.click()
el66 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"放松心灵\n11 min\")")
el66.click()
el67 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="放松")
el67.click()
el68 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"喜好意识\n10 min\")")
el68.click()
