el31 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"翻译通话\n您的智能助手\")")
el31.click()
el32 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="中文")
el32.click()
el33 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="日本語")
el33.click()
el34 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="English")
el34.click()
el35 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="中文")
el35.click()
el36 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="日本語")
el36.click()
el37 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="English")
el37.click()
el38 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="分享邀请链接")
el38.click()
