el1 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"会议记录\n转录和总结\")")
el1.click()
el2 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(11)")
el2.click()
el3 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="暂停")
el3.click()
el4 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="继续")
el4.click()
el5 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="标记")
el5.click()
el6 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="结束录制")
el6.click()
