el11 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"语音记录\n捕捉想法\")")
el11.click()
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(506, 472)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.pause(0.1)
actions.w3c_actions.pointer_action.release()
actions.perform()

el12 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(6)")
el12.click()
el13 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.EditText")
el13.click()
el13.clear()
el13.send_keys("12111")
el14 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="确定")
el14.click()
el15 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Button")
el15.click()
