el18 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"语音记录\n捕捉想法\")")
el18.click()
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(464, 481)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.pause(0.1)
actions.w3c_actions.pointer_action.release()
actions.perform()

el19 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="英语")
el19.click()
el20 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"中文（简体）\nChinese (Simplified)\")")
el20.click()
el21 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="中文")
el21.click()
el22 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"日本語\nJapanese\")")
el22.click()
el23 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="日语")
el23.click()
el24 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"English\nEnglish\")")
el24.click()
