el39 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"翻译通话\n您的智能助手\")")
el39.click()
el40 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="语音通话")
el40.click()
el41 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="中文")
el41.click()
el42 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="日本語")
el42.click()
el43 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="English")
el43.click()
el44 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="中文")
el44.click()
el45 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="日本語")
el45.click()
el46 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="English")
el46.click()
el47 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="分享邀请链接")
el47.click()
