el65 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的")
el65.click()
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(495, 844)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.move_to_location(503, 1939)
actions.w3c_actions.pointer_action.release()
actions.perform()

el66 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的账户")
el66.click()
el67 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.ImageView")
el67.click()
el68 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="从相册选择")
el68.click()
el69 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="合集")
el69.click()
el70 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(27)")
el70.click()
el71 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(15)")
el71.click()
el72 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(15)")
el72.click()
el73 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(4)")
el73.click()
el74 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="提交")
el74.click()
el75 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的账户")
el75.click()
el76 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.ImageView")
el76.click()
el77 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="拍照")
el77.click()
el78 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="快门")
el78.click()
el79 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="完成")
el79.click()
el80 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="提交")
el80.click()
