el32 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的")
el32.click()
el33 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="语音播报")
el33.click()
el34 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"语音播报语速\n1.20x\")")
el34.click()
el35 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="1.50x")
el35.click()
el36 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Button")
el36.click()
el37 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="语音播报")
el37.click()
el38 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"语音播报语速\n1.50x\")")
el38.click()
el39 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="1.20x")
el39.click()
el40 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Button")
el40.click()
