el13 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="历史")
el13.click()
el14 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="双耳机翻译")
el14.click()
el15 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="手机+耳机翻译")
el15.click()
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(891, 386)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.move_to_location(377, 397)
actions.w3c_actions.pointer_action.release()
actions.perform()

el16 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="单向翻译")
el16.click()
el17 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="图片翻译")
el17.click()
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(735, 369)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.move_to_location(282, 377)
actions.w3c_actions.pointer_action.release()
actions.perform()

el18 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="会议记录")
el18.click()
el19 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="语音记录")
el19.click()
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(112, 369)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.move_to_location(914, 377)
actions.w3c_actions.pointer_action.release()
actions.perform()

