el39 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的")
el39.click()
el40 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="操作指引")
el40.click()
el41 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="查看指引")
el41.click()
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(458, 1853)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.move_to_location(430, 877)
actions.w3c_actions.pointer_action.release()
actions.perform()

actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(475, 1975)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.move_to_location(472, 676)
actions.w3c_actions.pointer_action.release()
actions.perform()

el42 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="下一步")
el42.click()
el43 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="下一步")
el43.click()
el43.click()
el43.click()
el43.click()
el43.click()
el43.click()
el43.click()
el44 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="跳过")
el44.click()
