el43 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的")
el43.click()
el44 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="操作指引")
el44.click()
el45 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="手机+耳机模式")
el45.click()
el46 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="单项翻译模式")
el46.click()
el47 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="双耳机模式")
el47.click()
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(497, 1973)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.move_to_location(511, 872)
actions.w3c_actions.pointer_action.release()
actions.perform()

el48 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="手机+耳机模式")
el48.click()
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(478, 1889)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.move_to_location(539, 933)
actions.w3c_actions.pointer_action.release()
actions.perform()

actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(592, 2029)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.move_to_location(643, 1073)
actions.w3c_actions.pointer_action.release()
actions.perform()

el49 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="单项翻译模式")
el49.click()
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(489, 2029)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.move_to_location(514, 1129)
actions.w3c_actions.pointer_action.release()
actions.perform()

el50 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Button")
el50.click()
