el1 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"翻译中心\n面对面，无缝交流\")")
el1.click()
el2 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="开始手机模式")
el2.click()
el3 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="手机麦克风")
el3.click()
