el1 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"翻译中心\n面对面，无缝交流\")")
el1.click()
el2 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="开始双耳机模式")
el2.click()
el3 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="中文")
el3.click()
el4 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"日本語\nJapanese\")")
el4.click()
el5 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(10)")
el5.click()
el6 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(10)")
el6.click()
