el15 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"翻译中心\n面对面，无缝交流\")")
el15.click()
el16 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="开始单向模式")
el16.click()
el17 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="简体中文")
el17.click()
el18 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"English\nEnglish\")")
el18.click()
el19 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"English\").instance(1)")
el19.click()
el20 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"中文（简体）\nChinese (Simplified)\")")
el20.click()
el21 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(8)")
el21.click()
el22 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(8)")
el22.click()
