el14 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"翻译中心\n面对面，无缝交流\")")
el14.click()
el15 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="开始双耳机模式")
el15.click()
el16 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="English")
el16.click()
el17 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"한국어\nKorean\")")
el17.click()
el18 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(10)")
el18.click()
el19 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.view.View\").instance(10)")
el19.click()
