el1 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的")
el1.click()
el2 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的账户")
el2.click()
el3 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"生日\n2001-04-19\")")
el3.click()
el4 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="18, 2001年4月18日星期三")
el4.click()
el5 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="确定")
el5.click()
el6 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="提交")
el6.click()
