el5 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的")
el5.click()
el6 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的账户")
el6.click()
el7 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"用户名\n12313321321\")")
el7.click()
el8 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.EditText")
el8.click()
el8.clear()
el8.send_keys("12312332")
el9 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="确定")
el9.click()
el10 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="提交")
el10.click()
