el8 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的")
el8.click()
el9 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的账户")
el9.click()
el10 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"性别\n男\")")
el10.click()
el11 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="女")
el11.click()
el12 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="确定")
el12.click()
el13 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="提交")
el13.click()
el14 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的账户")
el14.click()
el15 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"性别\n女\")")
el15.click()
el16 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="其他")
el16.click()
el17 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="确定")
el17.click()
el18 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="提交")
el18.click()
