el61 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="我的")
el61.click()
actions = ActionChains(driver)
actions.w3c_actions = ActionBuilder(driver, mouse=PointerInput(interaction.POINTER_TOUCH, "touch"))
actions.w3c_actions.pointer_action.move_to_location(511, 1864)
actions.w3c_actions.pointer_action.pointer_down()
actions.w3c_actions.pointer_action.move_to_location(542, 553)
actions.w3c_actions.pointer_action.release()
actions.perform()

el62 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="帮助与支持")
el62.click()
el63 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="提交")
el63.click()
el64 = driver.find_element(by=AppiumBy.ACCESSIBILITY_ID, value="取消")
el64.click()
