el56 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().description(\"视频翻译\n社交媒体 AI\")")
el56.click()
el57 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(1)")
el57.click()
el58 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Button")
el58.click()
el59 = driver.find_element(by=AppiumBy.ANDROID_UIAUTOMATOR, value="new UiSelector().className(\"android.widget.Button\").instance(2)")
el59.click()
el60 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Switch")
el60.click()
el61 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Switch")
el61.click()
el62 = driver.find_element(by=AppiumBy.CLASS_NAME, value="android.widget.Button")
el62.click()
